apiVersion: v1
kind: Service
metadata:
  name: ws-service
  namespace: openfaas-fn
spec:
  type: ClusterIP
  selector:
    app: telar
    component: ws
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP